# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    disable_csrf_role: null
    param_fetcher_listener: true
    allowed_methods_listener: true
    routing_loader: false
    exception:
        enabled: true
    view:
        formats:
            json: true
            html: true
        mime_types:
            json: ['application/json']
            html: ['text/html']
        view_response_listener: 'force'
    body_listener:
        decoders:
            json: fos_rest.decoder.jsontoform
    format_listener:
        rules:
            - {
                  path: '^/admin/api',
                  priorities: ['json'],
                  fallback_format: json,
                  prefer_extension: false,
              }
            - {
                  path: '^/admin',
                  priorities: ['html'],
                  fallback_format: html,
                  prefer_extension: false,
              }
    service:
        serializer: fos_rest.serializer.jms
    serializer:
        serialize_null: true
