# Read the documentation: https://github.com/1up-lab/OneupUploaderBundle/blob/master/Resources/doc/index.md
oneup_uploader:
    mappings:
        media:
            frontend: dropzone
            storage:
                directory: '%kernel.project_dir%/public/uploads/media'
        parameter:
            frontend: dropzone
            storage:
                directory: '%kernel.project_dir%/public/uploads/parameter'
