kernel:
    resource: ../../src/Kernel.php
    type: annotation

admin_api_login_check:
    path: /admin/api/login_check

gesdinet_jwt_refresh_token:
    path: /admin/api/token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh

admin:
    resource: ../../src/Controller/Admin
    type: annotation
    prefix: admin/api

oneup_uploader:
    resource: .
    type: uploader
    prefix: /admin/api

controllers:
    resource: ../../src/Controller/Website
    type: annotation
