# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    jms_serializer.doctrine_proxy_subscriber.class: App\EventSubscriber\Admin\DoctrineProxySubscriber

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Hooks
    App\Hook\:
        resource: '../src/Hook'
        public: true

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    limenius_react.react_renderer:
        class: App\Utils\CustomPhpExecJsReactRenderer
        arguments:
            - '%kernel.project_dir%/public' # here you set the base path
            - '%limenius_react.fail_loud%'
            - '@limenius_react.context_provider'
            - '@logger'
        calls:
            - [setPackage, ['@assets.packages', 'build/app.js']]

    # Event Subscribers / Event Listeners
    App\EventSubscriber\Admin\ApiExceptionSubscriber:
        tags:
            - { name: kernel.event_subscriber }

    App\EventSubscriber\Admin\DoctrineSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    App\EventSubscriber\Admin\FileUploader:
        arguments:
            $rootPath: '%kernel.project_dir%'
        tags:
            - { name: kernel.event_subscriber, event: oneup_uploader.post_persist }

    App\EventSubscriber\Admin\FrontUrlSubscriber:
        tags:
            - { name: jms_serializer.event_subscriber }

    # Utils
    App\Utils\PathGetter:
        arguments:
            $projectDir: '%kernel.project_dir%'
