services:
    _defaults:
        autowire: true
        autoconfigure: true

    TicketFactory\Module\ModuleTest4\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
